USE Proj_DBMS_BookStore
SET XACT_ABORT ON
BEGIN TRAN
CREATE ROLE NV
GRANT UPDATE (SoLuong) ON dbo.HANG_HOA TO NV;
GRANT SELECT, REFERENCES ON dbo.NXB TO NV;
GRANT SELECT, REFERENCES ON dbo.VAN_PHONG_PHAM TO NV;
GRANT SELECT, INSERT, REFERENCES ON dbo.KHACH_HANG TO NV;
GRANT SELECT, UPDATE (SoDiem) ON dbo.THE_TV TO NV;
-- DENY REFERENCES ON dbo.NHAN_VIEN TO NV;
GRANT SELECT, REFERENCES ON dbo.TAI_KHOAN_DN TO NV;
GRANT SELECT, INSERT, REFERENCES ON dbo.LS_DANG_NHAP TO NV;
GRANT SELECT, INSERT, REFERENCES ON dbo.TAO_TV TO NV;
GRANT SELECT, INSERT, REFERENCES ON dbo.HOA_DON_BAN TO NV;
GRANT SELECT, INSERT, REFERENCES ON dbo.BAN_HANG TO NV;
GRANT EXECUTE ON dbo.PROC_Login TO NV;
GRANT SELECT ON dbo.FUNC_GetLoginHistory TO NV;
GRANT SELECT ON dbo.VIEW_SACH TO NV;
GRANT SELECT ON dbo.VIEW_THELOAISACH TO NV;
GRANT SELECT ON dbo.VIEW_VPP TO NV;


DENY SELECT ON dbo.VIEW_NV TO NV;
DENY SELECT ON dbo.VIEW_NV_TK TO NV;
DENY EXECUTE ON PROC_Register TO NV;
DENY EXECUTE ON PROC_NhapHang TO NV;
DENY EXECUTE ON FUNC_Create_MaHoaDonNhap TO NV;
COMMIT TRAN

SELECT ORIGINAL_LOGIN()
-- BEGIN TRAN 
-- 	  CREATE LOGIN [nvv1353] WITH PASSWORD = 'MK123456', DEFAULT_DATABASE = Proj_DBMS_BookStore, CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
-- 	  GO
-- 	  CREATE USER nvv1353 FOR LOGIN nvv1353
-- 	  GO
-- 	  ALTER ROLE NV ADD MEMBER nvv1353
-- 	  GO
-- COMMIT TRAN

SELECT * FROM tbl_login