USE master;
-- If DB exists, delete and create a new one
IF DB_ID('Proj_DBMS_BookStore') IS NOT NULL
	DROP DATABASE Proj_DBMS_BookStore
GO
CREATE DATABASE Proj_DBMS_BookStore
GO
USE Proj_DBMS_BookStore;
GO

-- MaNXB VARCHAR(10)
-- MaHang VARCHAR(20)
-- MaTG VARCHAR(10)
-- MaLoai VARCHAR(10)
-- MaNV VARCHAR(10)
-- MaThe VARCHAR(10) = MaKH


CREATE TABLE dbo.NXB(
	MaNXB VARCHAR(10) NOT NULL,
	TenNXB NVARCHAR(50) NOT NULL,
	DiaChi NVARCHAR(100) NOT NULL,
	SDT VARCHAR(15) NOT NULL CHECK(LEN(SDT) >= 10),
	
	PRIMARY KEY(MaNXB)
);
GO

CREATE TABLE dbo.HANG_HOA(
	MaHang VARCHAR(20) NOT NULL,
	DonGia INT NOT NULL CHECK(DonGia >= 1000),
	SoLuong INT NOT NULL CHECK(SoLuong >= 0),

	PRIMARY KEY(MaHang)
);
GO

CREATE TABLE dbo.VAN_PHONG_PHAM(
	MaHang VARCHAR(20) NOT NULL,
	TenHang NVARCHAR(50) NOT NULL,

	PRIMARY KEY (MaHang),
	FOREIGN KEY (MaHang) REFERENCES dbo.HANG_HOA(MaHang)
);
GO

CREATE TABLE dbo.SACH(
	MaSach VARCHAR(20) NOT NULL,
	TieuDe NVARCHAR(50) NOT NULL,
	MaNXB VARCHAR(10) NOT NULL,
	NamXB INT NOT NULL CHECK(NamXB > 1000),

	PRIMARY KEY (MaSach),
	FOREIGN KEY (MaSach) REFERENCES dbo.HANG_HOA(MaHang),
	FOREIGN KEY (MaNXB) REFERENCES dbo.NXB(MaNXB)
);
GO

CREATE TABLE dbo.TAC_GIA(
	MaTG VARCHAR(10) NOT NULL,
	TenTG NVARCHAR(50) NOT NULL,

	PRIMARY KEY (MaTG)
);
GO

CREATE TABLE dbo.TAC_GIA_SACH(
	MaSach VARCHAR(20) NOT NULL,
	MaTG VARCHAR(10) NOT NULL,

	PRIMARY KEY (MaSach, MaTG),
	FOREIGN KEY (MaSach) REFERENCES dbo.SACH(MaSach),
	FOREIGN KEY (MaTG) REFERENCES dbo.TAC_GIA(MaTG)
);
GO

CREATE TABLE dbo.THE_LOAI(
	MaLoai VARCHAR(10) NOT NULL,
	TenLoai NVARCHAR(20) NOT NULL,

	PRIMARY KEY (MaLoai)
);
GO

CREATE TABLE dbo.THE_LOAI_SACH(
	MaSach VARCHAR(20) NOT NULL,
	MaLoai VARCHAR(10) NOT NULL,

	PRIMARY KEY (MaSach, MaLoai),
	FOREIGN KEY (MaSach) REFERENCES dbo.SACH(MaSach),
	FOREIGN KEY (MaLoai) REFERENCES dbo.THE_LOAI(MaLoai)
);
GO

CREATE TABLE dbo.KHACH_HANG(
	MaKH VARCHAR(10) NOT NULL, -- Dung SDT lam ma KH
	Ho NVARCHAR(10) NOT NULL,
	TenLot NVARCHAR(10) NULL DEFAULT '',
	Ten NVARCHAR(10) NOT NULL,
	NgaySinh DATETIME NULL,
	GioiTinh NVARCHAR(3) NULL

	PRIMARY KEY (MaKH)
);
GO

-- Changed
CREATE TABLE dbo.THE_TV(
	MaThe VARCHAR(10) NOT NULL,
	SoDiem INT NOT NULL CHECK(SoDiem >= 0),
	-- TenBacTV NVARCHAR(10) NOT NULL DEFAULT 'Không có',
	MaKH VARCHAR(10) NOT NULL UNIQUE,

	PRIMARY KEY (MaThe),
	FOREIGN KEY (MaKH) REFERENCES dbo.KHACH_HANG(MaKH)
);
GO
ALTER TABLE dbo.THE_TV
ADD TenBacTV AS dbo.FUNC_Get_TenBac(SoDiem)

CREATE TABLE dbo.NHAN_VIEN(
	MaNV VARCHAR(10) NOT NULL,
	CMND VARCHAR(15) NOT NULL UNIQUE,
	Ho NVARCHAR(10) NOT NULL,
	TenLot NVARCHAR(10) NULL DEFAULT '',
	Ten NVARCHAR(10) NOT NULL,
	GioiTinh NVARCHAR(3) NULL,
	Luong INT NOT NULL DEFAULT 3000000 CHECK(Luong >= 1000),
	TinhTrangLamViec BIT NOT NULL,	-- 0: nghỉ; 1: đang làm

	PRIMARY KEY (MaNV)
);
GO

-- new table
CREATE TABLE dbo.TAI_KHOAN_DN(
	MaNV VARCHAR(10) NOT NULL,
	TenDN VARCHAR(20) NOT NULL UNIQUE,
	MK VARCHAR(30) NOT NULL CHECK(LEN(MK) >= 8),

	PRIMARY KEY (MaNV),
	FOREIGN KEY (MaNV) REFERENCES dbo.NHAN_VIEN(MaNV)
)

-- new table
CREATE TABLE dbo.LS_DANG_NHAP(
	TenDN VARCHAR(20) NOT NULL,
	ThoiGianDN DATETIME NOT NULL,

	PRIMARY KEY (TenDN, ThoiGianDN),
	FOREIGN KEY (TenDN) REFERENCES dbo.TAI_KHOAN_DN(TenDN)
);
GO

CREATE TABLE dbo.TAO_TV(
	MaNV VARCHAR(10) NOT NULL,
	MaThe VARCHAR(10) NOT NULL UNIQUE,
	MaKH VARCHAR(10) NOT NULL UNIQUE,
	NgayTao DATETIME NOT NULL,

	PRIMARY KEY (MaNV, MaThe, MaKH),
	FOREIGN KEY (MaNV) REFERENCES dbo.NHAN_VIEN(MaNV),
	FOREIGN KEY (MaThe) REFERENCES dbo.THE_TV(MaThe),
	FOREIGN KEY (MaKH) REFERENCES dbo.KHACH_HANG(MaKH)
);
GO

DROP TABLE dbo.TAO_TV

CREATE TABLE dbo.HOA_DON_NHAP(
	MaDonNhap VARCHAR(10) NOT NULL,
	ThoiGianNhap DATETIME NOT NULL,

	PRIMARY KEY (MaDonNhap),
);
GO

CREATE TABLE dbo.NHAP_HANG(
	MaDonNhap VARCHAR(10) NOT NULL,
	MaNVNhap VARCHAR(10) NOT NULL,
	MaHang VARCHAR(20) NOT NULL,
	SoLuong INT NOT NULL,

	PRIMARY KEY (MaDonNhap, MaNVNhap, MaHang),
	FOREIGN KEY (MaDonNhap) REFERENCES dbo.HOA_DON_NHAP(MaDonNhap),
	FOREIGN KEY (MaNVNhap) REFERENCES dbo.NHAN_VIEN(MaNV),
	FOREIGN KEY (MaHang) REFERENCES dbo.HANG_HOA(MaHang),
);
GO

CREATE TABLE dbo.HOA_DON_BAN(
	MaHoaDon VARCHAR(10) NOT NULL,
	ThoiGianBan DATETIME NOT NULL,
	KhuyenMai REAL NOT NULL,
	
	PRIMARY KEY (MaHoaDon)
);
GO

CREATE TABLE dbo.BAN_HANG(
	MaHoaDon VARCHAR(10) NOT NULL,
	MaNVBan VARCHAR(10) NOT NULL,
	MaKH VARCHAR(10) DEFAULT '0000000000' NOT NULL,
	MaHang VARCHAR(20) NOT NULL,
	SoLuong INT NOT NULL

	PRIMARY KEY(MaHoaDon, MaNVBan, MaKH, MaHang),
	FOREIGN KEY (MaHoaDon) REFERENCES dbo.HOA_DON_BAN(MaHoaDon),
	FOREIGN KEY (MaNVBan) REFERENCES dbo.NHAN_VIEN(MaNV),
	FOREIGN KEY (MaKH) REFERENCES dbo.KHACH_HANG(MaKH),
	FOREIGN KEY (MaHang) REFERENCES dbo.HANG_HOA(MaHang),
);
GO
